# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-12 08:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.TextField(default=b'', max_length=100)),
            ],
            options={
                'ordering': ['course_name'],
                'verbose_name': 'course',
                'verbose_name_plural': 'course',
            },
        ),
        migrations.CreateModel(
            name='KeyDefinition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.TextField(default=b'', max_length=100)),
                ('defination', models.TextField(default=b'', max_length=1000)),
            ],
            options={
                'ordering': ['lesson', 'keyword', 'defination'],
                'verbose_name': 'keyword',
                'verbose_name_plural': 'keyword',
            },
        ),
        migrations.CreateModel(
            name='Lessons',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson_name', models.TextField(default=b'', max_length=100)),
                ('paragraph', models.TextField(default=b'', max_length=1000)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paragraphxblock.Course')),
            ],
            options={
                'ordering': ['course', 'lesson_name', 'paragraph'],
                'verbose_name': 'lesson',
                'verbose_name_plural': 'lesson',
            },
        ),
        migrations.AddField(
            model_name='keydefinition',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paragraphxblock.Lessons'),
        ),
    ]
